name: Lighthouse
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Lighthouse
        id: lighthouseCheck
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: 'https://guruhotel-yelp-app.vercel.app/'
      - name: Verify Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minAccessibilityScore: '90'
          minBestPracticesScore: '90'
          minPerformanceScore: '90'
          minSeoScore: '90'
